# Generated by Django 3.0.11 on 2020-12-07 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='inauguration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 15, 34, 24, 861485)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sail',
            name='color',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sail',
            name='type',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
